export { default as FacebookIcon } from './facebook.svg'
export { default as InstagramIcon } from './instagram.svg'
export { default as TwitterIcon } from './twitter.svg'
export { default as YouTubeIcon } from './youtube.svg'
export { default as TikTokIcon } from './tiktok.svg'
export { default as LinkedInIcon } from './linkedin.svg'