import type { Metadata } from "next";

import "./global.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

export const metadata: Metadata = {
  title: "Moises",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetch("http://127.0.0.1:4000/global?locale=en");
  const globalData = await data.json();
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer
          helpText={globalData.helpText}
          copyrightText={globalData.copyright}
          social={globalData.social}
          footerMenu={globalData.footerMenu}
        />
      </body>
    </html>
  );
}
